### ISSUE TITLE
Add a visual indicator on the All Posts screen when a title or description is too long

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#110]
We currently have a visual indicator on the Edit Post / Edit Page screen when a title or description exceeds the recommended character limit (see screenshot).

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14178810/479b4c90-f72a-11e5-98f5-f8c87794617a.png)

We need a similar visual indicator on the All Posts / All Pages screen so that users can see at a glance which titles and descriptions are too long.  The mockup below shows how we could use the paperclip icon to display this.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14178971/1a978f0a-f72b-11e5-8879-286cdb066e56.png)

**Comment by michaeltorbert** [comment]
@wpsmort Would turning the paperclip red be a good indication of this? I don't know if that would be intuitive.

**Comment by nabtron** [comment]
How about showing the number of characters themselves instead of paperclip?

**Comment by michaeltorbert** [comment]
@nabtron I think that's a better idea, but I'm not sure if that scales should we want to include more information there.
In the near future, we'll have a per-post scoring system that rates how well you've completed various SEO tasks (including title length) for a given post/page. Ideally, that will be shown on this page as well, although not necessarily in the same place.

If we went with the number of characters, that may not solve the UI/UX issue of it not being obvious.
The paperclip is intended to be an intuitive way to let someone know they can edit the title/desc/keywords right there on the screen without opening the post. There are two problems with turning it red to indicate a problem with the length.
1) It's not intuitive what red means
2) Even if you know what red means, since the paperclip means that you can edit right there, a red paperclip would imply you can edit for the purpose of having an appropriate number of characters, which would require showing you the number of characters.

I think we need to give some more thought to the user experience here.
@wpsmort @arnaudbroes @dougalcampbell What are your thoughts?

**Comment by arnaudbroes** [comment]
I understand the concern that users will not know what the red paperclip means. 
However, as I said earlier, I am not a fan of too much text and a clustered UI.
However, I'm a fan of more visuals in the plugin (like this). 

Could it be possible to add a single, one-time notification to the dashboard of users the first time a title/description exceeds the character limit? I'd appreciate that as a user.
But like I said, I don't like too much text, because there has to be a limit. 
On the other hand, I think most users will understand what I means after it occurs a couple of times.

**Comment by nabtron** [comment]
Well if paperclip version is finalized, then we can have a tooltip on hover to show what it means

**Comment by wpsmort** [comment]
What if we do a notification message at the top that says "You have X number of SEO titles and X number of SEO descriptions that exceed the recommended character count.  Click here to view them."

If we did this, could we have a filter for the All Posts table that only shows those posts with SEO titles and/or descriptions that exceed the character count?  Then clicking on the notification would display the filtered posts.

**Comment by arnaudbroes** [comment]
I second Steve's suggestion. :-)

**Comment by wpsmort** [comment]
Here's a mockup of the notification message:

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/14465816/58372872-00a2-11e6-9624-42c3273dfa9f.png)

**Comment by nabtron** [comment]
Changes made @https://github.com/nabtron/all-in-one-seo-pack/blob/nabtron/inc/aioseop_functions.php from line# 790 - 952 to make this enhancement

**Comment by michaeltorbert** [comment]
@nabtron Your pull request needs to have an appropriate title and description, and the description needs to reference the issue number. Please see #166 for an example.

**Comment by nabtron** [comment]
updated :)

**Comment by michaeltorbert** [comment]
@wpsmort This is in the nabtron branch and is ready for testing. 

https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/185

**Comment by arnaudbroes** [comment]
@michaeltorbert 
Reviewed and can be code tested.

**Comment by wpsmort** [comment]
@michaeltorbert, I tested this and found three bugs:

1. The count of the number of errors always appears to be wrong.

2. The code is not taking into account the full length of the title based on the title format, so it doesn't count the | %blog_title% part of the title tag.  It only reports the title as too long if the post_title part of the title is over 60 characters.

3. If there are only SEO titles that exceed the maximum characters then the message is output and is correct but when you click on the link to view the Posts/Pages with long titles it returns an empty screen.

**Comment by wpsmort** [comment]
This has been moved to our new feature request system.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #908](https://github.com/awesomemotive/aioseop-pro/issues/908) via [**ZenHub**](https://www.zenhub.com/)
