### ISSUE TITLE
Canonical URLs broken for paged

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1313]
At least for the homepage. Reported via email by Marco.

"It is set to mysite.com/2/   mysite.com/3/   mysite.com/4/  instead of  mysite.com/page/2/  mysite.com/page/3/  mysite.com/page/4/"

We need to see if this is new or has always been there. I'm pretty sure it hasn't always been there... I want to say we had this problem at one time and then fixed it, maybe it broke again?

**Comment by wpsmort** [comment]
Reported again here - https://semperplugins.com/support/general-all-in-one-seo-pack-pro-forum/canonical-link-on-paginated-pages/

**Comment by wpsmort** [comment]
Update from the user who reported this:

I have checked the source code and found the following issue, which should be confirmed by the Dev Team, as they know the source code better. But I think this should be the solution/reason:

File: aioseop_class.php
Function: function get_paged( $link )
Line: 2778
Code: $link = trailingslashit( $link ) . “$page”;

This can not work correct, as the $link is give to the function like “https://www.mydomain.com”. Even if you call the page https://www.mydomain.com/paged/2 the $link is not given in that way to the function.

Problem in the if-case:

Line: 2777 => if ( $page == get_query_var( ‘page’ ) ) {

The get_query_var(‘page’) is only true on FRONTPAGE (Startpage) and never worked on a “category” page. So, the source code is not working. The variable $link has not the full URL (parameter “paged” is not included), so the given code “trailingslashit( $link ) . “$page”; can NOT work.

Instead of this:
```
if ( $page == get_query_var( ‘page’ ) ) {
$link = trailingslashit( $link ) . “$page”;
} else {
$link = trailingslashit( $link ) . trailingslashit( $page_name ) . $page;
}
```
Just use:
```
if ( ! empty( $page ) && $page > 1 ) {
  $link = trailingslashit( $link ) . trailingslashit( $page_name ) . $page;
  $link = user_trailingslashit( $link, ‘paged’ );
}
```

I could not find any issue on my test-website with this source code. The variable $link has not a “page_name” (/paged/), so the above should always work.

**Comment by wpsmort** [comment]
@arnaudbroes Can you reproduce the problem and then test the solution provided by the user.  If it works and doesn't break anything else then you can create a PR for this.

**Comment by arnaudbroes** [comment]
@wpsmort I'm not able to reproduce this. Tested with the homepage and a random page.
![image](https://user-images.githubusercontent.com/18156697/50044692-c52a9d00-0087-11e9-9b9f-253770cd050b.png)

**Comment by arnaudbroes** [comment]
@wpsmort this started happening in 2.2.6. However, in 2.2.4.1 we added support for this, but I believe there was a bug (?) at the time because the canonical URL of paginated pages refers to the last product that has been added (even if it's not featured on that page). So I'm guessing that this has been broken from the start.

**Comment by arnaudbroes** [comment]
Just a reminder to use the following steps to reproduce the issue:

1. Install AIOSEOP and WooCommerce
2. Enable SEO for Products in the General Settings menu
3. Add about a dozen test products
4. Go to the Customizer and reduce the amount of products per row and row per page
5. Set the shop page as the homepage
6. Check the source code. You'll see that the canonical URL ends on e.g. /2/ instead of /page/2

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #863](https://github.com/awesomemotive/aioseop-pro/issues/863) via [**ZenHub**](https://www.zenhub.com/)
