### ISSUE TITLE
Admin Help Text functionality on Frontend

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1315]
When running a breakpoint in the parent module class, I discovered the child classes are initiating the help text functionality. Which has no reason for it and only adds to the memory.

The Child Classes are using `All_in_One_SEO_Pack_Module::add_help_text_links()` method within it's class constructor.

To resolve this, wrap the function in an IF check with AIOSEOP Manage Cap/Role.

**Comment by EkoJr** [comment]
I've been running some tests of my own, and I've found that methods provided by WordPress doesn't prevent admin content 100% on the frontend (mostly because of the admin bar firing off of admin.php).

However, this does greatly reduce the number of loads and initiations.

`( defined( 'WP_ADMIN' ) && WP_ADMIN && is_blog_admin() )`

In order to prevent loading any unnecessary backend content, it may be possible to use the URL used with wp-admin (including altered file names) to identify the user is on wp admin.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #788](https://github.com/awesomemotive/aioseop-pro/issues/788) via [**ZenHub**](https://www.zenhub.com/)
