### ISSUE TITLE
Move CSS and Scripts to be enqueued as a file.

### ISSUE THREAD

**Issue by EkoJR** [awesomemotive/all-in-one-seo-pack#1394]
I notice there's some CSS and Scripts within various functions and class methods. Changing it to a CSS or JS file of its own would probably alleviate the amount of searching it would take to solve an issue, and would improve code quality itself with development. 

* For each class/module, I believe it would be separate JS/CSS files.
* All the variable with PHP have to be localized. Including any strings intended for translation.
    * Strings have to be translated when enqueueing scripts / localizing.
* Unless it is required to be in the Header, Scripts would be enqueue in the footer for anonymous scripting; adds compatibility ( example: jQuery UI ).

**Comment by michaeltorbert** [comment]
This is good, although it should probably be multiple issues.

**Comment by EkoJr** [comment]
Agreed. I noticed there are some option variables, and some callbacks that may need to handled separately.

**Comment by contactashish13** [comment]
@EkoJr I'm sure you've already thought of this but wanted to add this as suggestion just in case - if some JS/CSS is being included conditionally, then instead of adding these separate scraps to one big file, it is useful to have different files and register/localize all of them in one go to be enqueued later. So basically, instead of using wp_enqueue_script and wp_localize_script use wp_register_script and wp_localize_script and use wp_enqueue_script only when the file needs to be included.

**Comment by EkoJr** [comment]
@contactashish13 I was thinking instead of one big file, I was going to follow the module pattern just to keep it consistent. Possibly a Public JS, and the rest may end up in one file.  

I also use a similar pattern to where I try to keep things optimal and enqueue where needed, but I try not to repeat code by enqueuing multiple places. So, I usually try to catch it when it is first needed (and exclude when not needed). 

This was one of the concepts I recently applied, and is a bit different since it was using the screen hook to display a notice, but I was trying to apply the same restrictive measures.
https://github.com/EkoJr/all-in-one-seo-pack/blob/issue-43-61/admin/class-aioseop-notices.php#L183

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #793](https://github.com/awesomemotive/aioseop-pro/issues/793) via [**ZenHub**](https://www.zenhub.com/)
