### ISSUE TITLE
Social Meta - Add Social Media preview

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1489]
similar to Google SERPS preview (for Facebook at Twitter at least)

**Comment by EkoJr** [comment]
I may be mistaken, but I thought Facebook had multiple methods for displaying an article; same also goes for Google+.

I'm also wondering if this could be refined better with how data is handled, since the meta data itself being displayed is from base module code, and is applied in 3 different ways; which would be ideal, but has been problematic with the Descriptions release ( as well as OG module being rendered differently ).

Also, these might help for future reference.

* https://developers.facebook.com/tools/debug/
* https://developers.google.com/+/web/embedded-post/

**Comment by michaeltorbert** [comment]
This should happen after we've modified the UI to have tabs.

**Comment by wpsmort** [comment]
Moved to our feature request system.
