### ISSUE TITLE
UI - Improvements for the menus

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1735]
Having something like this could be nice https://www.jqueryscript.net/form/Nice-Checkbox-And-Radio-Button-Replacement-Plugin-nicelabel-js.html <img src="https://www.jqueryscript.net/images/Nice-Checkbox-And-Radio-Button-Replacement-Plugin-nicelabel-js.jpg" />
or https://www.jqueryscript.net/form/Custom-jQuery-Checbox-Radio-Input-Plugin-Custom-Checkbox.html

but in the meantime we could at least do something css-only like https://foundation.zurb.com/sites/docs/v/5.5.3/components/button_groups.html#
or http://freefrontend.com/css-radio-buttons/
or https://www.w3schools.com/howto/howto_css_custom_checkbox.asp
These should be pretty easy and quick to do as they're purely css
----------
more here https://www.jqueryscript.net/blog/Best-Checkbox-Radio-Input-Plugins.html and here 
https://www.jqueryscript.net/tags.php?/radio%20button/

**Comment by michaeltorbert** [comment]
We could also borrow from WordFence
<img width="1102" alt="screen shot 2019-02-09 at 4 08 26 pm" src="https://user-images.githubusercontent.com/17364998/52526345-14a2d900-2c85-11e9-834b-ca9137cc924b.png">

**Comment by arnaudbroes** [comment]
@michaeltorbert I'd be a big supporter of that.

**Comment by EkoJR** [comment]
I'd support this as well.

However, there is a concern with using a jQuery plugin. I use a jQuery plugin called a [Multiselect](https://github.com/ehynds/jquery-ui-multiselect-widget), and the biggest problems would be unmaintained code and little to no support; it has gotten better since the day it was added to github for others to contribute though.

I would probably recommend using [jQuery UI](https://jqueryui.com/) instead where it is possible, since WP does handles most of the tests and updates already. Plus, most of the render issues shouldn't be a problem. Then resort to plugins where needed.

When looking for a jQuery plugin, keep in mind to check to see it is on a public repository and is updated periodically.

**Comment by michaeltorbert** [comment]
In the WordFence image... 1) more modern looking metaboxes... we may be able to do it by just styling the existing metaboxes, or we may need to do something custom and move away from metaboxes 2) field elements themselves (checkboxes, radio buttons, etc) have more modern styling the save buttons stay put.

On the Gutenberg image, notice their nice big buttons. Those are not WP standard buttons, but they look great.

**Comment by arnaudbroes** [comment]
This PR (https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2512) also improves the menus quite a bit.
