### ISSUE TITLE
XML Sitemap excluded pages field doesn't work for attachment slugs

### ISSUE THREAD

**Issue by Dynatrace-Paul-Anderson** [awesomemotive/all-in-one-seo-pack#1744]
While the **Excluded Pages** field successfully excludes page slugs from the sitemap, it does not work when the slug is for an attachment.

I have a private page, which I've excluded from the sitemap by placing the page's slug in the **Excluded Pages** field. Unfortunately, the attachments on that page are still in the sitemap, so I need a way to exclude those pages as well. Adding the slugs for the permalink to the attachments, which are only used on this one private page, does not remove them from the sitemap.

**Comment by wpsmort** [comment]
I've checked this and found that there are potentially two issues here:

1).  We shouldn't include image attachments that are on a page set to Private.
2).  We should support IDs for attachments in the Excluded Pages field.

**Comment by michaeltorbert** [comment]
Are we talking about the images themselves or the attachment pages?
Also, let's keep in mind that media can potentially be attached to multiple pages, so we'd need to think about how to handle that.

**Comment by wpsmort** [comment]
We're talking about attachment pages.  I would say that if an image is attached to two pages and one is public and one is private then the attachment page should be included in the sitemap.  However, if both pages were private then it should not be included.  I agree that this could get complicated though.

**Comment by michaeltorbert** [comment]
Yeah that's probably the way to go.

**Comment by dkomando** [comment]
I'm having this issue as well.  

I cannot exclude an attachment from the auto-generated sitemap.xml with a every comma separated URL or slug variation I can think of. 

The problem is Google Search Console is reporting it as an error and is asking me to remove or fix the page. Which the plugin is not allowing me to do. 

I'm taking it, that this is very low priority since its still under "Initial Review" six plus months later.

**Comment by michaeltorbert** [comment]
@dkomando 
This isn't a higher priority in part because many people tend to not include attachment pages in their XML sitemaps, and will probably be the default behavior eventually anyway.
Having said that, development is funded by people who purchase All in One SEO Pack Pro from semperplugins.com, so there aren't unlimited development resources to go around, yet there's an endless supply of new features to implement, bugs to fix, etc, so it simply isn't possible to do everything right away. Every single one of the 600+ issues is important to someone. 
This is an open source project though, so you're welcome to submit code yourself via a PR, which would help ensure it happens sooner.

**Comment by dkomando** [comment]
Understood. Thanks for the clarification.

**Comment by wpsmort** [comment]
I tested this and found that you can now exclude media attachment pages by using slugs or IDs in the Excluded pages field.

I've opened a feature request though to automatically exclude media attached to private or password protected posts.
