### ISSUE TITLE
Bug - Redirect image to post parent results in 404 for unattached image

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1834]
Reported here: https://wordpress.org/support/topic/google-serp-index-of-images/#post-10584444

We need to discuss and figure out what, if anything, we should do for unattached images.

**Comment by arnaudbroes** [comment]
@michaeltorbert I was able to reproduce this on a new test site.

![image](https://user-images.githubusercontent.com/18156697/45257689-8c08cf80-b3aa-11e8-9759-37ee3d72a339.png)

**Comment by contactashish13** [comment]
what kind of a fix are we thinking of here?

**Comment by michaeltorbert** [comment]
@contactashish13 I don't know, it's open for discussion. The only thing I can think of to do off the top of my head is to check first if there's anywhere to redirect it to.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1910

If the attachment post's parent post is deleted or unavailable, it will be redirected to the image itself.

**Comment by wpsmort** [comment]
I've been unable to reproduce this on any of my sites or on a new site.  Any time I have an unattached image, I cannot produce a 404 error.  It correctly opens the image attachment page. 

@arnaudbroes Can you reliably reproduce this?  If so, can you provide the steps.  Can you reproduce this with the new block editor in WP 5.x?

Here's my two cents on this:

1. I would want to know that we can reliably reproduce this before we consider doing anything.
2. I'd expect WordPress to correctly handle links to unattached images (which is what I see in my testing) so there should be no reason for us to interfere.
3. If WordPress isn't handling this, then why not?  Is it caused by AIOSEO?  If it's not caused by AIO, then we shouldn't get involved.  If it is, then it's a bug and we should be able to reproduce it and fix it (i.e. get out of the way and let the link open the image attachment page).

**Comment by arnaudbroes** [comment]
@wpsmort I tried reproducing this in two test enviroments. I played around with a few versions of the plugin and WordPress, but I'm no langer able to reproduce this issue.

**Comment by michaeltorbert** [comment]
The user happens to be a Pro user, so I'm emailing him to ask for login info.

**Comment by wpsmort** [comment]
The user who reported this submitted login information.  I took a look and here are some notes on what I found with this specific site:

- The Media Library on this site contains 408 images, only two images were unattached. 
- Of the two unattached images, I could not reproduce the reported bug with either.  For example, there's an image called Wheat which is unattached and is in the XML Sitemap.  Clicking on the URL in the sitemap results in the image attachment page being displayed correctly.
- However, looking in search results for this site, there are lots of images that are indexed and which result in a 404 error. These are attached images that correctly redirect to their post parent but Google has indexed the original attachment page URL.

Here's an example (I've obscured the domain name for customer privacy reasons):

Google has the attachment page URL indexed as https://domain.com/mike_dickinson/ which results in a 404 page
The Media Library has the permalink as https://domain.com/our-team/mike_dickinson/ and this is attached to the Our Team page
The XML Sitemap lists the this same URL and when you browse to it, you are correctly redirected to the parent page
Unchecking the Redirect Attachment to Parent option results in the image attachment page being displayed correctly https://domain.com/our-team/mike_dickinson/

The problem is that Google seems to indexing the original URL for the image attachment page prior to the image being attached to a post/page, so when an image gets attached, the URL changes resulting in a 404 for the original URL indexed by Google.

**Comment by wpsmort** [comment]
Reported again by email from Bill Connors.

I got access to Bill's site and found that there were images in the Media Library which were unattached and which resulted in a 404 page when viewing them.  I was able to use the Media Library Assistant plugin (https://wordpress.org/plugins/media-library-assistant/) to identify that these media attachments all had an invalid parent page which no longer existed. However, I'm still unable to reproduce this on my site.

**Comment by michaeltorbert** [comment]
Correct me if I'm wrong, but to sum up, we have problems with 
a) media is unattached
b) media is attached to a non-existant page

Proposed solution:
Redirect to the image itself if there's no attached page or attached page doesn't exist.

**Comment by wpsmort** [comment]
Yes, those two instances are where we have problems.  The proposed solution works for me.

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/sitemap-has-nonexistent-pages/.  I was not able to reproduce this with a backup of the customer site. 

However, using the Media Library Assistant and looking in the database I was able to see that media was attached to posts that had been deleted.  When I looked in the wp_posts table for the post ID, the post showed up with a status of published.

**Comment by michaeltorbert** [comment]
This happens in edge cases. We need to figure out what that edge case is to reliably reproduce it in a real world scenario. @wpsmort Assign it back to me for dev.

**Comment by wpsmort** [comment]
I've now got some steps to reliably reproduce this:

1. Create a new site and install a plugin that creates a custom post type such as Envira Gallery (you can also use the CPT UI plugin to create a custom post type
2. Create a gallery in Envira Gallery or create a post in your CPT
3. Upload a brand new image to the gallery or to the content of the post
4. Verify in the Media Library that the image is attached to the gallery or post
5. View the XML Sitemap and look for the attached images in the attachment-sitemap.xml
6. Ensure that you have Redirect Attachments to Post Parent and then click on the links and you should be redirected to the parent 
7. Now deactivate Envira Gallery or delete the custom post type
8. Go to the Media Library and you'll see that it now says (Private post) in the Uploaded to column for your images
9. Now go to the sitemap and click on the link and you'll get a 404 page.  

The key here is where it shows the image is attached to (Private post), this is incorrect, WordPress should really say something like (Invalid post) or (Non-existant post).  The problem is the post still exists in the wp_posts table and has a status of Published because it was never deleted, it's just that the post type no longer exists.  

This happens with themes that create custom post types such as Portfolio and then you change the theme and that post type no longer exists but all the posts and their attached images still exist.

**Comment by arnaudbroes** [comment]
Seen again on Sanjay M.'s website.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #897](https://github.com/awesomemotive/aioseop-pro/issues/897) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this to our new repo for dev team to work on.
