### ISSUE TITLE
Bug - If a post is in Draft, an attachment id query string is generated to the sitemap even if the image is attached

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#1835]
Reported at: https://wordpress.org/support/topic/google-serp-index-of-images/#post-10584444

**Comment by arnaudbroes** [comment]
@michaeltorbert I was able to reproduce and confirm this on a new test site.

![image](https://user-images.githubusercontent.com/18156697/45257620-82329c80-b3a9-11e8-88e8-3ff56a08b732.png)

**Comment by contactashish13** [comment]
@arnaudbroes I'm not able to reproduce this. Can you please mention the steps?

PS - It would be of immense help if you can write down the steps whenever you are able to reproduce an issue as it would save a lot of time and hunting through the issue (sometimes in vain :smile:)

**Comment by arnaudbroes** [comment]
@contactashish13 here are the steps to reproduce:

1. Create a new Post
2. Upload a new image and add it in the content of the Post (this is referred to as "attaching")
3. Save to Post to Draft
4. Go to the General Setting menu, scroll down to the Advanced Settings section and enable "Redirect attachments to post parent"
5. View the sitemap as a non-logged in user and click the attachment ID URL (for the image).
You'll be redirected to a 404 because the image is redirecting to it's post parent which is in Draft.

Expected behaviour: attachment URLs for images that are attached to Posts that aren't published shouldn't appear in the sitemap since they'll result in a 404.

**Comment by contactashish13** [comment]
PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2003

**Comment by michaeltorbert** [comment]
Related to #1810 #1834 

In 1834 we need to redirect to the image URL itself if the attachment is unattached
In this issue, we need to redirect to the image URL if the post parent is not published

**Comment by wpsmort** [comment]
Reported again here - https://wordpress.org/support/topic/attachments-of-draft-posts-in-sitemap/

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #896](https://github.com/awesomemotive/aioseop-pro/issues/896) via [**ZenHub**](https://www.zenhub.com/)

**Comment by wpsmort** [comment]
I've moved this to our new repo for the dev team to work on.
