### ISSUE TITLE
API - aioseop_attachment_size filter doesn't always work

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2080]
Reported here: https://wordpress.org/support/topic/image-size-for-sharing-on-social-media/

From looking at the code, the filter only fires on get_the_image_by_attachment()
I *think* that the image settings have to be configured to attachment, and then on the post itself, don't select an image.

**Comment by onetarek** [comment]
While looking at the function `get_the_image_by_attachment()` I have found an unnecessary line of code
`$alt   = trim( strip_tags( get_post_field( 'post_excerpt', $id ) ) );`

https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/admin/aioseop_module_class.php#L1627

**Comment by michaeltorbert** [comment]
Needs reproducing instructions.

**Comment by wpsmort** [comment]
Steps to reproduce:

1. Create a post with an attached image, an image in the content, and a featured image
2. Go to All in One SEO > Social Meta > Image Settings and set the OG:Image Source as Default Image, check the box for Use Default If No Image Found and upload a default image that's large enough so that a large, medium and thumbnail size image are created
3. View the source code of the post and verify that the og:image is the full size default image
4. Use the filter to set the returned image size as thumbnail
5. View the source code of the post and see if the og:image is displaying the thumbnail
6. Go back to the Image Settings and repeat these steps with the other selections in the Select OG:Image Source drop down

By following these steps above, you'll see that the only images affected by the filter are the first attached image and the first image in content.

The filter needs to also affect the default image, featured image and first available image.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #901](https://github.com/awesomemotive/aioseop-pro/issues/901) via [**ZenHub**](https://www.zenhub.com/)
