### ISSUE TITLE
XML Sitemap - Improve sitemaps for multi-language sites

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#2131]
Related to #941.

Currently we create different sitemaps for each language.  We do this regardless of whether the translated content is in subdirectories, subdomains or their own domains.

For sites where translated content is in subdirectories, Google recommends including every language variation for each URL in the same sitemap.  Here is Google's article about this - https://support.google.com/webmasters/answer/189077?hl=en

We should look at implementing this and ensuring compatibility with WPML, Polylang, qTranslate and any other translation plugin we are compatible with.

There's a good article about this here - https://wplang.org/sitemaps-multiple-languages-wordpress/

**Comment by evimistry** [comment]
"Currently we create different sitemaps for each language. We do this regardless of whether the translated content is in subdirectories, subdomains or their own domains."

I am currently using Polylang and All in one seo(both basic) but it dosent create another sitemap rather than for default language. Is this feature only avaible to paid version??

**Comment by wpsmort** [comment]
@evimistry We have a separate issue open to support Polylang https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/941

**Comment by wpsmort** [comment]
Replaced by #102
