### ISSUE TITLE
Bug - Post Title Format is ignored for posts with no title

### ISSUE THREAD

**Issue by Lawtaker** [awesomemotive/all-in-one-seo-pack#2134]
One of my blogs consists of a series of fairly short notes on current events and suchlike. I do not set the titles for them.

When both the WP and the SEO Pack titles of a post are missing, SEO Pack ignores the Post Title Format setting. For example, it may be

%blog_title% | %post_author_firstname% %post_author_lastname%

But it fails to rewrite the title to that or any other value in that textbox. If SEO Pack custom title is present though not the WP title, then it works. Even setting the SEO Pack title to " " (space) works.

But I'd like the plugin to rewrite the title to whatever's in Post Title Format even if both the WP title and the SEO Pack custom title are empty strings.

**Version Info (please complete the following information):**
 - WordPress version: 5.0.3
 - All in One SEO Pack version: 2.10.1
 - PHP version: 7.2.13

**Comment by arnaudbroes** [comment]
I was able to reproduce this. 

In order to reproduce the issue, follow these steps:
1. Install All in One SEO Pack on a fresh test site
2. Go to the General Settings menu and enter the following format in the Post Title Format input field: %blog_title% | %post_author_firstname% %post_author_lastname%
3. Create a new Post or Page without an H1 (title) or SEO title and you'll see that the title only consists of the blog title
