### ISSUE TITLE
General - Default social/SEO to enabled for taxonomies

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#2814]
Related to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1584

Make sure this doesn't change anything for existing sites.

**Comment by wpsmort** [comment]
I discussed this with Michael and we agreed to push this out to 3.4.  

The only way to do this is to swap the logic throughout the plugin so that wherever we check for which post types are checked, we swap this to check for which are unchecked, and vice versa.

Note that in the database we store the option as this:

aiosp_opengraph_types {
	i:0;s:4:"post";
	i:1;s:4:"page";
}
