### ISSUE TITLE
General - Check compatibility with PHP v7.4

### ISSUE THREAD

**Issue by arnaudbroes** [awesomemotive/all-in-one-seo-pack#2835]
It's due on November 28. Soon after it's released we should check if Travis CI is supporting it and add it to our build matrix.

**Comment by arnaudbroes** [comment]
Closing this since PHPCompatibility will take care of this for us. Their already working on support for PHP 7.4 - https://github.com/PHPCompatibility/PHPCompatibility/issues/808

**Comment by michaeltorbert** [comment]
Since WP 5.3, due out in November, will support PHP 7.4, we probably need to do some explicit manual testing by installing PHP 7.4 to make sure we don't have any issues. 

WordPress itself had to fix a number of them:
https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=closed&status=new&status=reopened&status=reviewing&keywords=~php74&milestone=5.3&order=priority
https://core.trac.wordpress.org/ticket/47746
https://core.trac.wordpress.org/ticket/47751
https://core.trac.wordpress.org/ticket/47783
https://core.trac.wordpress.org/ticket/47704
