### ISSUE TITLE
Conflict - Performance of Divi affected

### ISSUE THREAD

**Issue by messynaman22** [awesomemotive/all-in-one-seo-pack#3089]
I have updated the same and the issue seems to be resolved. After the recent release, I noticed my website is slowed down when I use your plugin. Seems like your plugin is taking up lot of resources or has some confliction with Divi Theme. I already had word with Divi Support Team and they said the issue is connected with the plugin and they won't be able to provide support for that. Can you check your plugin compatibility with Divi Themes?

**Comment by wpsmort** [comment]
@messynaman22 We need more information from you.  Please fill out the form below as completely as possible so that we can help you more quickly:

**Provide the relevant URL(s) here**

**Describe the bug**
A clear and concise description of what the bug is.
What happened?
What did you expect to happen?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version Info (please complete the following information):**
 - WordPress version:
 - All in One SEO Pack version:
 - PHP version:
