### ISSUE TITLE
when I click on the link to see site map on Chrome nothing is showing

### ISSUE THREAD

**Issue by alexmojnov74** [awesomemotive/all-in-one-seo-pack#3153]
Should I see some information there?

**Comment by wpsmort** [comment]
@alexmojnov74 This is a development repository. We don't answer support questions here.

Check the source code (right click and select View Page Source), if you see the XML Sitemap there then it's fine, you just can't see the human readable sitemap.  The most common cause of this is because the XSL stylesheet doesn't load which can be caused by incorrect implementation of SSL where the XSL file is loading using HTTP and not being redirected to HTTPS.  You can see errors related to this in the Chrome error console.
