### ISSUE TITLE
Deprecated Filters Detected: "aiosp_disable"

### ISSUE THREAD

**Issue by qualmy91** [awesomemotive/all-in-one-seo-pack#3183]
One of our users reached out at our [forum](https://www.asgaros.de/support/topic/new-wordpress-all-in-one-seo-but-asgaros/) because he got a warning that our Plugin "Asgaros Forum" is using the deprecated filter "aiosp_disable". I've checked your code here, but it seems like the filter is still available:

https://github.com/awesomemotive/all-in-one-seo-pack/blob/04682bf9c95ca80cab41bf83410c71acefa5ddec/aioseop_class.php#L4090

Can you please give me short feedback if it's just a false alarm or if have to use another filter to deactivate AIOSP at our plugin?

**Comment by arnaudbroes** [comment]
Hey @qualmy91,

Thank you for reaching out.

We just launched a complete new version (rebuild) of the plugin where we removed all old filters and added new ones so that our naming is consistent going forward. In the previous version, we had all kinds of different prefixes like aiosp_, aioseo_ and aioseop_

The new filter hook is `aioseo_disable`. You'll want keep the old one (to assure backwards compatibility) and just add the new one in addition to it.

Feel free to reach out again if you need any help.

- Arnaud

**Comment by qualmy91** [comment]
Hey @arnaudbroes, 

am I right that the notification will still be shown to every user if we just add the second filter to our source code?

Or do you also check if there are both filters used?

**Comment by arnaudbroes** [comment]
@qualmy91 that's a good point. You should probably add a check to see which version of AIOSEO is active. 

You can add a check to see if the` AIOSEOP_VERSION` constant is defined for the old hook, and if the `AIOSEO_VERSION` constant is defined for the new one.

**Comment by qualmy91** [comment]
Can you please also let me know the version number of the rebuild? So I can add it to our code.

**Comment by arnaudbroes** [comment]
@qualmy91 the rebuild starts at 4.0.0. Here's also a doc on the new filter - https://aioseo.com/docs/aioseo_disable/
