### ISSUE TITLE
Uncaught TypeError: array_replace_recursive() with PHP 8.0

### ISSUE THREAD

**Issue by innocenat** [awesomemotive/all-in-one-seo-pack#3193]
I sometimes got this error when editing older articles. My setup is PHP 8.0.

```
PHP message: PHP Fatal error:  Uncaught TypeError: array_replace_recursive(): Argument #2 must be of type array, null given in /var/www/**/public/wp-content/plugins/all-in-one-seo-pack/app/Common/Models/Model.php:494

PHP message: PHP Fatal error:  Uncaught TypeError: array_replace_recursive(): Argument #2 must be of type array, null given in /var/www/**/public/wp-content/plugins/all-in-one-seo-pack/app/Common/Models/Model.php:611
```

I added `if ($existingOptions === null) $existingOptions = [];` prior to those line as a hot-fix myself.

**Comment by arnaudbroes** [comment]
@innocenat this is part of a larger, seldomly occurring issue that our team has been working on. The cause of the issue is fixed, but there's some slight data corruption that occurred on your site. Please contact our support team at the following link (click the "Submit a Form" button) - they'll be more than happy to clean the data for you.
https://aioseo.com/contact
