### ISSUE TITLE
The aiosp_opengraph_meta filter isn't working – cannot re-write og:url...

### ISSUE THREAD

**Issue by E-VANCE** [awesomemotive/all-in-one-seo-pack#3204]
Dear AIOSEO-team,

we have been using the `aiosp_opengraph_meta`-filter in order to re-write the **og:url** that is being output by the plugin based on certain conditions (date, post ID).

It seems now that the filter isn't working any more...?

I went ahead and searched the docs and the web for any hints as well as checked the source code for any mentions but couldn't fine none (besides some code referencing a deprecated image handler).

The [link to the corresponding doc article](https://aioseo.com/docs/aiosp_opengraph_meta/?v3) is dead & there is no mention when searching for the filter nor a comprehensive overview of the available filters...

Is the filter completely deprecated? Any other way of re-writing the **og:url** then?

Thanks & regards
_Henning_

**Comment by arnaudbroes** [comment]
Hey @E-VANCE,

Most filter hooks have been replaced since version 4.0.0, which is when we launched a completely rewritten version of the plugin. We couldn't keep the old hooks in place because the data structures have changed massively. 

You should be to rewrite the Open Graph URL again using this hook - https://aioseo.com/docs/aioseo_facebook_tags/. On that doc page, you'll find examples of how you can use this hook, but let me know in case something isn't completely clear.

**Comment by E-VANCE** [comment]
Many thanks – that did the trick!

Maybe you could redirect the old doc article accordingly or reference the change there?
