### ISSUE TITLE
Migrate to start accepting OpenAI project keys instead of api key

### ISSUE THREAD

**Issue by perinm** [awesomemotive/all-in-one-seo-pack#3221]
Right now it returns a message saying:

"The API key you have entered is invalid. Please check your API key and try again."

This is necessary for better cost tracking of open ai usage.

![image](https://github.com/user-attachments/assets/40274134-ac4a-4c91-8f67-2433ff9752e1)

**Comment by arnaudbroes** [comment]
@perinm this should be fixed in our next update, which is rolling out next Thursday. Please reopen the issue if it still appears broken after you've pulled in the update.

Feel free to contact us through our free Basic Question form at https://aioseo.com/contact in case you'd like to get a beta build and try it out already.
