### ISSUE TITLE
aioseop_yst_detected_notice_dismissed() seems to be loading on every page

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#340]
according to query monitor, aioseop_yst_detected_notice_dismissed happens even on the front-end, which results in a mysql query... not only should this not happen on every pageload, it should never happen on the front-end

**Comment by EkoJr** [comment]
I had taken a look at the code while working on a related issue, and it relies on two factors.

* If 'WPSEO_Import_Hooks' class does not exist.
* If `is_admin()`.

I ran into this issue before, and it is because of the admin_bar at the top; which I believe was traced back to `admin-ajax`. There's one concept I haven't implemented yet, but I was tempted to write a ticket to WP Core to propose a function `is_wp_admin()` instead. Since `is_admin()` is technically suppose to be true on the frontend via `admin-ajax`.

I'm split between this being a WP bug, and valid concept; which needs an enhancement / different function proposed on WP Core to check specifically if user is on wp-admin.

**Comment by michaeltorbert** [comment]
@EkoJr  So short of waiting on a change to core, do you have a recommendation?

**Comment by contactashish13** [comment]
@EkoJr @michaeltorbert I have a suggestion: Instead of using 

```
add_action( 'init', ...
```
maybe it should be using

```
add_action( 'admin_init', ...

```
and if its a problem of ajax, we can consider checking for the constant DOING_AJAX

**Comment by EkoJr** [comment]
There was another issues that resulted in a Notice Management object, and the method for displaying the Notices is encapsulated in a admin notice hook.

https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/61#issuecomment-342017293
