### ISSUE TITLE
Consolidate notices

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#43]
We have a ton of overlapping but separate functions to handle notices. Consolidate these so all notices are using the newer and better stuff instead of our custom legacy notice system of functions. Make sure there are enough arguments for dismissible, type (warning, updated, etc)...

**Comment by mrtorbert** [comment]
Classes should be accepted as a possible array and should include: notice-error, notice-warning, notice-info, update-nag, is-dismissible, etc

**Comment by michaeltorbert** [comment]
Related to #25

**Comment by michaeltorbert** [comment]
check out github.com/collizo4sky/persist-admin-notices-dismissal

**Comment by michaeltorbert** [comment]
We also need to make sure we support <4.2 (which may have been the problem with our prior woocommerce notices not dismissing)

**Comment by EkoJr** [comment]
@michaeltorbert I noticed this issue similar to 'Add a 5 star ratings request' #61, and wanted to request assigning this.

I am aware of most of the notices by now, and took a look at the Repo for Persistant Admin Notice Dismissal. The other repo seems to apply a similar concept by working off a time-lapse, and uses a dismissal variable. Then saves it as wp_options. Not too much different than what is already in development.

One other thought that did occur to me though, is...

* Making the dismissal unique to users. So, multiple Admins users can dismiss the notice without it dismissing for others that would otherwise act on the notice.

**Comment by michaeltorbert** [comment]
I've assigned this two you, but we should be careful about possible conflicts. It's probably best to wait until the other one is finished before doing this.

Offhand I'd say some notice dismissals may be unique to users, but most are probably site wide.

**Comment by EkoJr** [comment]
Understood. I was curious if I should wait for the other branch.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #774](https://github.com/awesomemotive/aioseop-pro/issues/774) via [**ZenHub**](https://www.zenhub.com/)
