### ISSUE TITLE
All logging should be our own file

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#660]
Our log function should start writing to a log file instead of the database or error log as appropriate.
We should figure out ways of tagging certain information...
For example using JSON (even better is ndjson):

[{date:'2012-01-01 02:00:01', severity:"ERROR", msg:"Foo failed"},
{date:'2012-01-01 02:04:02', severity:"INFO", msg:"Bar was successful"},
{date:'2012-01-01 02:10:12', severity:"DEBUG", msg:"Baz was notified"},

http://ndjson.org/

**Comment by michaeltorbert** [comment]
`
$date = date("Y-m-d h:m:s");
$file = __FILE__;
$level = "warning";
 
$message = "[{$date}] [{$file}] [{$level}] Put your message here".PHP_EOL;
// log to our default location
error_log($message);
 
// error.log
[2015-08-14 09:08:23] [/var/www/html/index.php] [warning] My error message here!

function logger($message, array $data, $logFile = "error.log"){    
    foreach($data as $key =&gt; $val){   
      $message = str_replace("%{$key}%", $val, $message);    
      }    
      $message .= PHP_EOL;    
 
    return file_put_contents($logFile, $message, FILE_APPEND); } 
 
logger("%file% %level% %message%", ["level" =&gt; "warning", "message" =&gt;"This is a message", "file" =&gt;__FILE__]);
`

**Comment by michaeltorbert** [comment]
This is a good UI for logging. See how they do it... file or db.

<img width="1068" alt="screen shot 2016-12-07 at 5 02 24 pm" src="https://cloud.githubusercontent.com/assets/17364998/20988494/03c0305e-bc9f-11e6-893f-840554cfba03.png">

**Comment by contactashish13** [comment]
@michaeltorbert I would suggest logging in the database as a transient field with a limited timespan of X minutes (X ~ 10 minutes). This would also be triggered only when debug / similar flag is enabled.

**Comment by contactashish13** [comment]
@michaeltorbert I've worked on an implementation of this PR https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/2204 and this is how it looks (just an example)

![image](https://user-images.githubusercontent.com/12953439/52853628-30552600-3142-11e9-833b-367dec8fa2ff.png)

The salient points are:

- it logs in the database because I don't think using the filesystem is reliable when it comes to different hosting providers. As a backup and for testing on local/dev instances, it also logs to error log
- it logs into one transient variable. It logs the last 100 requests (configurable through a filter) and caches them upto 5 minutes (configurable through a filter)
- it logs only when the Log events is checked otherwise it does not log
- the implementation provided is both as an action hook (preferable) and as a function so that it can be extended further if required. 
`
do_action( 'aiosp_log', 'some error message', 'warn', __FILE__, __LINE__ );
`

- the radio buttons can be used to toggle what kind of logs to see. This filter is through CSS/JS not through ajax
- it captures the location (file and line number) of the log statement
- a download functionality can also be added that downloads the logs as a CSV file for users to send the logs to us
- if this looks fine, future code should contain `do_action` hooks invoking this wherever needed so that debugging becomes easier if someone sends us the log file.


comments welcome @arnaudbroes @wpsmort @EkoJR

**Comment by michaeltorbert** [comment]
Personally my preference would be to log to a file, with the understanding that it may not work on some crappy hosts. This way we can use the WP Filesystem API.
I'm certainly open to discussion on it though.

Also, I'd change the radios to checkboxes so that multiple ones can be selected (obviously "all" would deselect the reset).

**Comment by arnaudbroes** [comment]
I'm fine with both ideas although a text file would have my preference as well since that's easily accessible via SFTP.

**Comment by michaeltorbert** [comment]
@arnaudbroes That was my thinking. log files are easier to work with, send, etc.
They can also be easily deleted instead of filling up the db. I worry about runaway log entries killing a db.

**Comment by arnaudbroes** [comment]
I wasn't even thinking about log entries running wild. Yes, we should definitely log to a file instead ofthe database. I only see this causing unwanted issues otherwise.

**Comment by wpsmort** [comment]
I also agree that this should be logging to a file rather than the database and that the radios be changed to checkboxes and remove the All option.  

What file and file location will this log to?  In our help for the Log events option it says the all-in-one-seo-pack.log file in its plugin directory.  Should we change the location to /wp-content/ so it's in the same location as the WordPress debug log?

**Comment by michaeltorbert** [comment]
I'd definitely change it to wp-content.
We may also want to have a constant AIOSEOP_DEBUG_LOG which can be set to a custom path in wp-config.

**Comment by contactashish13** [comment]
I think we take files to be easy to work with because of our familiarity and not any technical reasons. Writing to files is costly as compared to databases. Clearing files is costly. Any file operation is costly. Using g transients you reduce all that effort so I'm not cconvinced. Is there a strong technical reason I'm missing?

**Comment by michaeltorbert** [comment]
I mentioned technical reasons above. They're also easier for users to use, send, etc.
There's definitely a resource overhead cost of writing to files vs database, but presumably logging wouldn't be running all the time on a production site, only for development, staging, etc.

**Comment by contactashish13** [comment]
Not sure easier to work with qualifies as a technical reason :) That's more of user friendliness than a technical reason for preference or efficiency.

**Comment by michaeltorbert** [comment]
> I worry about runaway log entries killing a db.

I'd rather have excessive log entries make a 10GB file than a 10GB db.

**Comment by contactashish13** [comment]
Not gonna happen with the constraints I mentioned. Log length and log expiry. Maybe you can check the code to see what's happening and how it works to reassure yourself it's not just random forget and insert into the database.

**Comment by michaeltorbert** [comment]
Out of curiosity, why did you choose to store the logs as transients rather than something proprietary, and why do you recommend they be stored for only 10 minutes?
-----
Interestingly, WooCommerce does both file and database:
https://github.com/woocommerce/woocommerce/blob/master/includes/log-handlers/class-wc-log-handler-db.php 
https://github.com/woocommerce/woocommerce/blob/master/includes/log-handlers/class-wc-log-handler-file.php

**Comment by contactashish13** [comment]
I chose transients because the cleanup pf those is handled by WP automatically. Also because I don't want them cached as regular options are auto cached.

Caching for 5 minutes and using only the last 100 logs are just a random numbers and can be increased or decreased using the filters.

**Comment by EkoJR** [comment]
Well, 5 minutes doesn't leave much time, and a lot of errors are caught after the fact.

I also think it would be best to make it an OOP class. Which seems to be what WooCommerce did.

I'm also concerned if this creates multiple transients instead of 1. Each transient save and load is an SQL query, which results in a higher time and memory. With the Sitemap Optimization to attachments, I kept it as a static variable to load 1 time, and a hook on shutdown to save the data.

**Comment by michaeltorbert** [comment]
@EkoJR I think he just meant that he randomly put down a number to be figured out later, not that he specifically wanted that time. ;)

**Comment by wpsmort** [comment]
Replaced by #3003
