### ISSUE TITLE
Notification Center - XML Sitemap - Message about correct rewrite rules when site is in subdirectory

### ISSUE THREAD

**Issue by wpsmort** [awesomemotive/all-in-one-seo-pack#789]
Reported here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/dynamic-sitemap-generation-does-not-appear-to-be-using-the-correct-rewrite-rules/

When a site is in a subdirectory, there is a message in the XML Sitemap > Sitemap Status box that says:

Dynamic sitemap generation does not appear to be using the correct rewrite rules; please disable any other sitemap plugins or functionality on your site and reset your permalinks.

Despite this message, the XML Sitemap seems to be working fine.  We need to determine why this message appears and whether it should be removed.

**Comment by wpsmort** [comment]
@arnaudbroes:  Can you help test this.  We need to go back through versions of AIOSEOP and see if this message has always been present.  I tested back to version 4.2 of WordPress and version 2.2.7 of AIOSEOP and the message was there.

Contact me and I'll help you with setting up a test site in a subdirectory.

**Comment by arnaudbroes** [comment]
I've just traced this back with different versions of WordPress and the plugin. 
The issue has been present since the introduction of the sitemap module. 
However, it seems like the plugin wasn't able to generate the sitemap either before 2.3 when wordpress isn't nested in root but in a subfolder. 

So in short:
- 2.2.x : sitemap doesn't work, message present
- 2.3.x : sitemap works, message still present

**Comment by michaeltorbert** [comment]
@arnaudbroes So the sitemap used to not work (meaning the message was correct at one time in this instance)? 
When did that change?

**Comment by arnaudbroes** [comment]
@michaeltorbert 
So when WordPress is nested into a subfolder and permalinks are turned on, the sitemap doesn't seem to work at all in 2.2x. If a new one is generated (updated), it just outputs a blank page. 
So I am guessing that's due to incorrect rewrite rules. This is up to 2.2.7.6.2.

In 2.3 (and onward) the sitemap is generated correctly and the message is definitely redundant.

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #831](https://github.com/awesomemotive/aioseop-pro/issues/831) via [**ZenHub**](https://www.zenhub.com/)
