### ISSUE TITLE
Fatal error in certain instances with new compatibility classes

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#896]
A user is getting a fatal error 
Fatal error: Class ‘All_in_One_SEO_Pack_Compatible’ not found in /home/aitrey/public_html/wp-content/plugins/all-in-one-seo-pack/inc/compatability/compat-wpml.php on line 12

The error appears even with all other plugins deactivated and Twenty Seventeen active. Interestingly, the plugin activates with no problem if the plugin directory is renamed.

Also, this can't be reproduced, even when restoring from a backup of this user's site on our own servers.

**Comment by amostajo** [comment]
After testing this locally and on the live server (where the issue was detected), I found out that the issue was due to server's cache and not the plugin.

# Test details
[ReflectionClass](http://php.net/manual/en/class.reflectionclass.php) was used to check the abstract class existence and the results were logged in a file.

```php
//--------
// Check with reflection the abstract class is present.
$comp = new ReflectionClass( 'All_in_One_SEO_Pack_Compatible' );
ini_set( 'log_errors', 1 );
ini_set( 'error_log', ABSPATH . '/error_log.log' );
error_log( sprintf(
	'[DEBUG] - Abstract class "All_in_One_SEO_Pack_Compatible" %sexists. File reference: %s. Reflection structure: %s',
	( $comp->isAbstract() ? '' : 'doesn\'t ' ),
	__FILE__,
	json_encode( [
		'filename'	=> $comp->getFileName(),
		'name'		=> $comp->getName(),
		'namespace'	=> $comp->getNamespaceName(),
	] )
) );die;
//--------
```

The piece of code above was added to:
* After line 391 in [all_in_one_seo_pack.php](https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/all_in_one_seo_pack.php#L391)
* After line 140 in [inc/compatability/compat-init.php](https://github.com/semperfiwebdesign/all-in-one-seo-pack/blob/master/inc/compatability/compat-init.php#L140)

## Test results
Results varied depending the plugin's folder. When using:
* `all-in-one-pack` as folder, the plugin did not exit on the `die;` clause, prompting the error of *Class Not Found* when loading file `inc/compatability/compat-init.php`. Suggesting that the server executed a different version of the file.
* `all-in-one-pack1` as folder, the site went blank when executing the `die;` clause. The expected behavior.

## Conclusion
Test results point to a server cache issue, not plugin related.

**Comment by michaeltorbert** [comment]
As this is a server caching issue, I'm closing this for now.

**Comment by michaeltorbert** [comment]
Response from Liquid Web:

Hello,

`My name is Calvin and I will be assisting you with finding information about what caching method your server utilizes. Here is what I've found so far:

    [root@host ~]# php -vPHP 5.6.29 (cli) (built: Dec 31 2016 00:06:57) Copyright (c) 1997-2016 The PHP GroupZend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies    with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd., and    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies

It appears your server is utilizing Zend Opcache. I also went a step further and provided the Opcache configuration settings you have enabled in you server's php.ini file.

    opcache.memory_consumption=32opcache.interned_strings_buffer=8opcache.max_accelerated_files=7963opcache.revalidate_freq=0opcache.fast_shutdown=0opcache.enable_cli=1opcache.enable=1opcache.validate_timestamps=0

Let me know if you have any further questions or concerns regarding this. Thank you and have a nice rest of your day!

Regards,
(Robert) Calvin Wallace
Linux Support Technician`

**Comment by amostajo** [comment]
Here is documentation about [OPcache](http://php.net/manual/en/book.opcache.php) for future references.

This issue might be solved by simply calling [opcache_reset](http://php.net/manual/en/function.opcache-reset.php):
```php
opcache_reset();
```

Again, a server issue.

**Comment by michaeltorbert** [comment]
@amostajo opcache_reset() does fix it, but (and I'm talking about for future updates, not for this particular user) the problem would be where to put it. In the main plugin file doesn't work (and we wouldn't want to reset the cache on every load anyway).
We have aioseop_updates_class.php, but who knows whether that runs soon enough (it depends on where the moved/added file is that's breaking things in the first place.

**Comment by amostajo** [comment]
@michaeltorbert My humble opinion is that this should not be something concerning the plugin code-wise, because the plugin could be updated N times and you will never know how and which files are being cached by users' servers. This time, was `all-in-one-pack.php`, next time and in other server could be one of the module classes. If this is given a priority, the you will have to take in consideration all files and all forms of caching, which I think is has nothing to do with the plugin's functionality.

I think this should be mentioned in some sort of F.A.Q. section int the documentation.
