### ISSUE TITLE
Improve default Twitter card settings and behavior

### ISSUE THREAD

**Issue by michaeltorbert** [awesomemotive/all-in-one-seo-pack#993]
First reported/requested here: https://wordpress.org/support/topic/bug-twitter-card-summary-large-image-ignored

Currently, we have two Twitter card settings: 
1) Global setting in the site's Social Meta menu
2) Post setting in Social tab

The behavior is currently that, whichever is set in the global setting, is what the post-specific setting defaults to for new posts. However, there's no override for existing posts. (This could be done with filter hooks.)

We should discuss whether to a) add such an override, b) remove this setting, and add an override in its place, c) just encourage the use of filter hooks, or d) ?

**Comment by charlesrr** [comment]
For now, could you just add some help text to mention that "it doesn't affect previous pages and posts and that it can be done in the meta tab on old pages and post"? (arrived here while trying to figure out why I couldn't update my homepage to "large" card via the global settings. I don't think many people would want to go back and change many old posts because they have already chosen images that are appropriate to the shape (large = rectangular, standard = square).

**Comment by wpsmort** [comment]
Reported again here - https://semperplugins.com/support/troubleshooting-all-in-one-seo-pack-pro/twitter-card-not-showing-large-image/

**Comment by michaeltorbert** [comment]
One thing to consider is at least having a way to mass override. Unfortunately we probably can't just change the behavior for an existing setting.

**Comment by wpsmort** [comment]
Moving this to our new Github repo

**Comment by wpsmort** [comment]
Issue moved to [awesomemotive/aioseop-pro #845](https://github.com/awesomemotive/aioseop-pro/issues/845) via [**ZenHub**](https://www.zenhub.com/)
